export {default as Header } from "./Header"
export {default as Hello} from "./HelloWorld"
export {default as Footer} from "./Footer"
export {default as Login} from "./Login"
export {default as Cadastrar} from "./Cadastrar"
